language: python
python:
  - 3.6.5
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database business_test_db;' -U postgres
script:
  #- coverage run app_tests.py
  - coverage run manage.py testv1
   
after_success: coveralls