"""empty message

Revision ID: 2061929c3ed9
Revises: 397b12c0b0f4
Create Date: 2018-02-28 02:22:30.115095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2061929c3ed9'
down_revision = '397b12c0b0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_name', table_name='business')
    op.create_index(op.f('ix_business_name'), 'business', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_name'), table_name='business')
    op.create_index('ix_business_name', 'business', ['name'], unique=True)
    # ### end Alembic commands ###
